import type {
  Experiment,
  TaskRequest,
  TaskWithPosition,
} from "../../generated/queue";
import type { QueueTableData } from "./tableData";

export function calculateNewPosition(
  oldPosition: number, // Position in queue
  oldIndex: number, // Row index in table
  targetIndex: number,
): number {
  const newPosition = Math.max(oldPosition + (targetIndex - oldIndex), 0);

  return newPosition;
}

// Should be autogenerated, see https://github.com/DiamondLightSource/atlas/issues/160
interface Sample {
  positionInContainer: {
    position: string;
  };
  container: {
    positionInParent: {
      position: string;
    };
  };
}

export function positionFromSample(sample: unknown): string {
  const s = sample as Sample;
  const pin = s.positionInContainer.position;
  const puck = s.container.positionInParent.position;
  return `Puck ${puck} | Pin ${pin}`;
}

export function getTableData(
  tasksToDisplay: TaskWithPosition[],
): QueueTableData[] {
  return (
    tasksToDisplay.map((task) => {
      if (task.kind === "Experiment") {
        const exp = task.experiment as Experiment;

        return {
          task: task,
          position: task.position,
          name: exp.name,
          id: task.id,
          instrumentSession: task.experiment.instrument_session,
          sampleId: exp.sample.id,
          samplePosition: positionFromSample(exp.sample),
          density: exp.sample.data.density as number,
          beamSize: exp.experiment_definition.data.focused_beam_size as number,
          timePerPDF: exp.experiment_definition.data.time_per_pdf as number,
          status: task.status,
        };
      } else {
        const plan = task.experiment as TaskRequest;

        return {
          task: task,
          position: task.position,
          name: plan.name,
          id: task.id,
          instrumentSession: task.experiment.instrument_session,
          sampleId: "",
          samplePosition: "",
          density: null,
          beamSize: null,
          timePerPDF: null,
          status: task.status,
        };
      }
    }) ?? []
  );
}
