ui-base:
  name: p99
  host: p99.diamond.ac.uk

  image:
    repository: ghcr.io/diamondlightsource/atlas/p99
    tag: # Updated by CI job with latest release version

  # Note that if these have changed you may need to manually restart the oauth2-proxy pod on deployment
  upstreams:
    - id: blueapi
      path: /api/blueapi/
      rewriteTarget: /
      target:
        external:
          uri: https://p99-blueapi.diamond.ac.uk/

    - id: supergraph
      path: /api/supergraph
      target:
        external:
          uri: https://graph.diamond.ac.uk

  authConfigFlags: |
    skip_auth_routes = ["GET=^/$", "GET=^/assets"]
    api_routes = ["^/oauth2", "^/api"]
    skip_provider_button = true
